name: Workflow caches warmup

on:
  workflow_dispatch:
    inputs:
      reason:
        description: The reason for dispatching it manually.
        type: string
        default: manual healthcheck
        required: true

  schedule:
    - cron: 30 6 1 * * # at 06:30 on day-of-month 1, UTC

jobs:
  cache:
    name: Caching deps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with: { fetch-depth: 0 }
      - name: Set up Go environment
        uses: actions/setup-go@v4
        with: { go-version: 1.20.x, cache-dependency-path: src/*/go.sum, check-latest: true }

      - name: Fetch dependencies
        run: make list
        env:
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}

  notify:
    name: Notifying
    needs: [ cache ]
    runs-on: ubuntu-latest
    if: failure() || success()

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with: { fetch-depth: 0 }

      - name: Send notification
        uses: ./.github/actions/notify
        continue-on-error: true
        with:
          emoji: ♻️
          channel: ${{ secrets.SLACK_WEBHOOK }}
          success: ${{ ! contains(needs.*.result, 'failure') }}
